name: Deploy Preview

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PREVIEW_TOKEN }} 
          external_repository: puffin-zero-preview/puffin-zero-preview.github.io
          publish_branch: main
          publish_dir: .
          force_orphan: true
